# 1. Create a 3x3x3 array with random values 

In [43]:
import numpy as np
x=np.random.uniform((3,3,3))
print(x)

[2.30594353 1.94223438 2.29805166]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [44]:
a=np.diag(1+np.arange(4),k = -1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [45]:
b=np.zeros((8,8),dtype=int)
b[1::2,::2]=1
b[::2,1::2]=1
print(b)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [46]:
z=np.random.random((5,5))
zmax,zmin=z.max(),z.min()
z=(z-zmin)/(zmax-zmin)
print(z)

[[0.09173153 0.00134208 0.89056437 0.5978844  0.2728896 ]
 [0.37303026 0.11737473 0.         0.20139049 0.2481507 ]
 [0.10122182 0.05210123 0.18210117 0.53057483 0.8351759 ]
 [0.25543585 0.30053384 0.6314543  0.10095495 0.80272858]
 [0.7953471  0.1531188  1.         0.33801664 0.99662939]]


# 5.  How to find common values between two arrays?

In [47]:
array1=np.array([11,21,27,9,7,18])
print("array1:",array1)
array2=np.array([11,65,21,90,17,4])
print("array2:",array2)
print("common values between two arrays:")
print(np.intersect1d(array1,array2))


array1: [11 21 27  9  7 18]
array2: [11 65 21 90 17  4]
common values between two arrays:
[11 21]


# 6.How to get the dates of yesterday, today and tomorrow?

In [48]:
yesterday=np.datetime64("today","D")-np.timedelta64(1,'D')
print("yesterday:",yesterday)
today=np.datetime64("today","D")
print("Today:",today)
tomorrow=np.datetime64("today","D")+np.timedelta64(1,'D')
print("tomorrow:",tomorrow)


yesterday: 2020-07-26
Today: 2020-07-27
tomorrow: 2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [49]:
A=np.random.randint(0,2,5)
B=np.random.randint(0,2,5)
equal=np.allclose(A,B)
print(equal)

False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [50]:
z=np.array((1,2,3,4,5,6,7,8,9,10))
z[z.argmax()]=0
print(z)

[1 2 3 4 5 6 7 8 9 0]


# 9. How to print all the values of an array?

In [51]:
arr=np.ones((5,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# 10.Subtract the mean of each row of a matrix

In [52]:
x=np.random.rand(5,10)
y=x-x.mean(axis=1,keepdims=True)
#y=x-x.mean(axis=1).reshape(-1,1)
print(y)

[[-0.14542187  0.30488449  0.38430783 -0.35756026 -0.07710359  0.51632627
  -0.01281695 -0.38856674  0.01569924 -0.23974843]
 [ 0.38799526  0.08273418 -0.17522053  0.364329   -0.53036205 -0.37131991
   0.23644888  0.24568588  0.24485379 -0.48514451]
 [ 0.51597131  0.14016404  0.23164513  0.39956308 -0.14674224 -0.37226428
  -0.26888454 -0.29729933 -0.36866471  0.16651155]
 [-0.23807371 -0.4005244  -0.0245177   0.22682828  0.2690502   0.0553828
   0.39642418 -0.13047409 -0.34310471  0.18900914]
 [-0.15931516 -0.10021463 -0.10908661  0.17084705 -0.29622952 -0.07005604
   0.41992922  0.07303634 -0.00901453  0.08010388]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [53]:
z=np.ones(10)
i=np.random.randint(0,len(z),20)
z += np.bincount(i,minlength=len(z))
print(z)

[2. 3. 6. 3. 3. 3. 5. 1. 2. 2.]


# 12.How to get the diagonal of a dot product?

In [54]:
A=np.random.randint(0,10,(3,3))
B=np.random.randint(0,10,(3,3))
np.diag(np.dot(A,B))

array([36, 36, 64])

# 13.How to find the most frequent value in an array?

In [55]:
f=np.random.randint(0, 10,40)
print("original array:")
print(f)
print("most frequent value in the above array:")
print(np.bincount(f).argmax())

original array:
[5 2 9 6 0 5 6 0 3 1 4 8 1 1 7 8 4 5 8 3 1 7 4 0 9 9 1 9 7 0 0 2 6 4 4 3 8
 7 2 9]
most frequent value in the above array:
0


# 14.How to get the n largest values of an array

In [56]:
x=np.arange(20)
print("original array:")
print(x)
np.random.shuffle(x)
n=1
print(x[np.argsort(x)[-n:]])

original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[19]


# 15.How to create a record array from a regular array?

In [57]:
d=np.array([("hello",2,3),("world",4,7),("letsupgrade",5,8)])
print("original arrays:",d)
print("\nrecord array:")
e=np.core.records.fromarrays(d.T,names='col1,col2,col3',formats='S80,f8,i8')
print(e)

original arrays: [['hello' '2' '3']
 ['world' '4' '7']
 ['letsupgrade' '5' '8']]

record array:
[(b'hello', 2., 3) (b'world', 4., 7) (b'letsupgrade', 5., 8)]
